
import React, { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import { report_tableApi } from "../api";
import "../style/circletable.css";
import { downloadAveragesPdf } from "../utils/pdfBRSRReport";

interface SubmittedReport {
  report_id: number;
  district_id: number;
  division_name: string;
  manager_name: string;
  phone: string;
  file_path: string;
  created_at: string;
  generated_by_user: string;
  address?: string;
}

const Circletable: React.FC = () => {
  const [reports, setReports] = useState<SubmittedReport[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  // Get token from Redux
  const token = useSelector((state: any) => state.auth.token);

  useEffect(() => {
    const fetchReports = async () => {
      // Check if token exists
      if (!token) {
        setError("Authentication token not found. Please log in again.");
        setLoading(false);
        return;
      }

      try {
        const result = await report_tableApi.getSubmittedReports(token);
        setReports(result.reports || []);
        setLoading(false);
        setError(null);
      } catch (error) {
        console.error("Error loading submitted reports:", error);
        setError("Failed to load reports. Please check your authentication.");
        setLoading(false);
      }
    };
   
    
    fetchReports();
  }, [token]);
  
   useEffect(() => {
  const applyHeaderStyles = () => {
    const headers = document.querySelectorAll('.branches-table thead th');
    headers.forEach(header => {
      (header as HTMLElement).style.backgroundColor = '#1e293b'; // Match sidebar
      (header as HTMLElement).style.color = 'white';
      (header as HTMLElement).style.textAlign = 'center';
    });
  };
  
  applyHeaderStyles();
  const timer = setTimeout(applyHeaderStyles, 100);
  
  return () => clearTimeout(timer);
}, [reports]);
  const formatDate = (dateString: string) => {
    return new Date(dateString).toLocaleDateString('en-GB');
  };

 const handleDownload = async (divisionId: number, divisionName: string, managerName: string) => {
  try {
    if (!token) {
      console.error("No token found");
      return;
    }

    const result = await report_tableApi.getDivisionReport(divisionId, token);

    if (result.averages && result.averages.length > 0) {
      const averages = { ...result.averages[0], address: result.address }; 

      downloadAveragesPdf(
        averages,
        divisionName,       // pass division name
        managerName,        // pass manager name
        "BRSR_Report"   // title
      );

      console.log(`Division ${divisionId} report:`, averages);
    } else {
      console.warn("No averages found in API response");
    }
  } catch (error) {
    console.error("Error fetching division report:", error);
  }
};



  if (loading) return <p className="loading-text">Loading Submitted Reports...</p>;
  
  if (error) return <p className="error-text">{error}</p>;

  return (
    <div className="circle-table-container">
      {/* Table Section */}
      <div className="table-section">
        <div className="table-header">
          <h3>Submitted BRSR Reports</h3>
        </div>

        <div >
          <table className="branches-table">
            <thead>
              <tr>
                <th>Report ID</th>
                <th>Division Name</th>
                <th>Manager Name</th>
                <th>Phone</th>
                <th>Submitted On</th>
                <th>Generated By</th>
                <th>Take Action</th>
              </tr>
            </thead>
            <tbody>
              {reports.length > 0 ? (
                reports.map((report) => {
                  const filename = report.file_path ? report.file_path.split('/').pop() || `report_${report.report_id}.pdf` : `report_${report.report_id}.pdf`;
                  
                  return (
                    <tr key={report.report_id}>
                      <td>{report.report_id}</td>
                      <td>{report.division_name}</td>
                      <td>{report.manager_name}</td>
                      <td>{report.phone}</td>
                      <td>{formatDate(report.created_at)}</td>
                      <td>{report.generated_by_user}</td>
                      <td>
                        <button
                          onClick={() => handleDownload(
                            report.district_id,       // divisionId
                            report.division_name,     // divisionName
                            report.manager_name       // managerName
                          )}
                          className="action-btn download-btn"
                        >
                          Download PDF
                        </button>

                      </td>
                    </tr>
                  );
                })
              ) : (
                <tr>
                  <td colSpan={7} className="no-data">
                    No reports submitted yet
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
};

export default Circletable;

